import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faMugSaucer } from '@fortawesome/free-solid-svg-icons/faMugSaucer'

config.autoAddCss = false

export default function Home() {
  return (
    <>
      <Head>
      <title>Coffeenap</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
      <div className={styles.center}>
        <FontAwesomeIcon icon={faMugSaucer} color="#785e22" size='10x' />
        Coffee. Nap. Wake up going a million miles an hour.
      </div>
      <div className={styles.footer}>
        Image by <a href="https://www.freepik.com/free-vector/flat-design-comic-style-background_12065075.htm#query=radial%20background&position=2&from_view=keyword">Freepik</a>
      </div>
    </main>
    </>
  )
}
